on:
  workflow_call:
    secrets:
      ACUITY_PASS:
        required: true
      ACUITY_USER:
        required: true
      GMAIL_PASS:
        required: true
      GMAIL_RECEPIENTS:
        required: true
      GMAIL_SEND_ADDRESS:
        required: true

jobs:
  pass-secret-to-workflow:
    uses: ./.github/workflows/windows_build.yml
    secrets:
       ACUITY_PASS: ${{ secrets.ACUITY_PASS }}
       ACUITY_USER: ${{ secrets.ACUITY_USER }}
       GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
       GMAIL_RECEPIENTS: ${{ secrets.GMAIL_RECEPIENTS }}
       GMAIL_SEND_ADDRESS: ${{ secrets.GMAIL_SEND_ADDRESS }}

