name: Remind Client

on:
  workflow_dispatch: # Allows for manual triggering

jobs:
  build:
    runs-on: windows-latest
    environment: test

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: pip install -r requirements.txt
    
    - name: Run the script
      run: py remind-client.py
      env:
        DB_CONN: ${{ secrets.DB_CONN }}
        GMAIL_REMINDER_SENDER: ${{ secrets.GMAIL_REMINDER_SENDER }}
        GMAIL_REMINDER_SENDER_PASS: ${{ secrets.GMAIL_REMINDER_SENDER_PASS }}
