name: Send Survey

on:
  # push:
  #   branches:
  #     - send-survey
  # pull_request:
  #   branches:
  #     - send-survey
  workflow_dispatch: # Allows for manual triggering
  schedule:
      - cron: '0 17 * * *'  # Runs every day at 5pm Central Standard Time (CST)

jobs:
  build:
    runs-on: windows-latest
    environment: test

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: pip install -r requirements.txt
    
    - name: Run the script
      run: py main.py
      env:
        ACTIONS_RUNNER_DEBUG: true
        ACTIONS_STEP_DEBUG: true
        ACUITY_PASSWORD: ${{ secrets.ACUITY_PASS }}
        ACUITY_USER: ${{ secrets.ACUITY_USER }}
        GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
        GMAIL_RECEPIENT_1: ${{ secrets.GMAIL_RECEPIENT_1 }}
        GMAIL_RECEPIENT_2: ${{ secrets.GMAIL_RECEPIENT_2 }}
        GMAIL_RECEPIENT_3: ${{ secrets.GMAIL_RECEPIENT_3 }}
        GMAIL_SURVEY_SENDER: ${{ secrets.GMAIL_SURVEY_SENDER}}
        GMAIL_SURVEY_SENDER_PASS: ${{ secrets.GMAIL_SURVEY_SENDER_PASS}}
        DB_ENDPOINT: ${{ secrets.DB_ENDPOINT }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_PASS: ${{ secrets.DB_PASS }}
        DB_USER: ${{ secrets.DB_USER }}      
