name: Trigger-Update-Database

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch: # Allows for manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: No Operation Step
      run: echo "This workflow only serves to trigger another workflow."

