name: Trigger-Update-Database

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch: # Allows for manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: No Operation Step
      run: echo "This workflow only serves to trigger another workflow."

    - name: Trigger Database Update on Dev Branch
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/:JacobZCodes/:TutorsBilling/actions/workflows/update_database.yaml/dispatches \
          -d '{"ref":"update-database"}'
