name: Trigger-Update-Database

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch: # Allows for manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: No Operation Step
      run: echo "This workflow only serves to trigger another workflow."

    - name: Trigger Database Update on Dev Branch
      run: |
        curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/JacobZCodes/TutorsBilling/actions/workflows/update_database.yml/dispatches \
            -d '{"ref":"update-database"}'
