name: Trigger-Update-Database

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
    - name: Triggered workflow
      run: echo "This workflow only triggers another workflow and does nothing else."
