name: Trigger-Remind-Client
on:
  push:
    branches:
      - remind-client
  schedule:
    - cron: '0 15 * * 1'  # Runs Monday at 9AM CST
  workflow_dispatch: # Allows for manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: No Operation Step
      run: echo "This workflow only serves to trigger another workflow."

    - name: Trigger Remind Client on remind-client branch
      run: |
        curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/JacobZCodes/TutorsBilling/actions/workflows/remind-client.yml/dispatches \
            -d '{"ref":"remind-client"}'
