name: Trigger-Send-Survey

on:
  schedule:
    - cron: '0 23 * * *'  # Runs every day at 5PM CST
  workflow_dispatch: # Allows for manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: No Operation Step
      run: echo "This workflow only serves to trigger another workflow."

    - name: Trigger Send Survey on send-survey branch
      run: |
        curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/JacobZCodes/TutorsBilling/actions/workflows/send-survey.yml/dispatches \
            -d '{"ref":"send-survey"}'
