name: Windows Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Call reusable workflow to set secrets
      uses: ./.github/workflows/pass_secrets.yml
      secrets: inherit

    - name: Run the script
      run: py process.py
      env:
        ACUITY_PASSWORD: ${{ secrets.ACUITY_PASS }}
        ACUITY_USER: ${{ secrets.ACUITY_USER }}
        GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
        GMAIL_RECEPIENTS: ${{ secrets.GMAIL_RECEPIENTS }}
        GMAIL_SEND_ADDRESS: ${{ secrets.GMAIL_SEND_ADDRESS }}
