name: Windows Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    environment: test

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Set up Chromedriver
      uses: nanasess/setup-chromedriver@v2

    - name: Start Chromedriver
      run: chromedriver --url-base=/wd/hub &

    - name: Run the script
      run: py process.py
      env:
        ACTIONS_RUNNER_DEBUG: true
        ACTIONS_STEP_DEBUG: true
        CHROMEDRIVER_PATH: ${{ env.CHROMEDRIVER_PATH }}        
        ACUITY_PASSWORD: ${{ secrets.ACUITY_PASS }}
        ACUITY_USER: ${{ secrets.ACUITY_USER }}
        GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
        GMAIL_RECEPIENTS: ${{ secrets.GMAIL_RECEPIENTS }}
        GMAIL_SEND_ADDRESS: ${{ secrets.GMAIL_SEND_ADDRESS }}
      
